"""Sovereign Script Code Generator — AST to Python.

Generates executable Python from the Sovereign Script AST.
Injects a prelude with builtin functions: cx_remember, cx_recall,
sov_emit, sov_run, print.
"""
from __future__ import annotations

from sovereign_lang.parser import (
    Pipeline, Let, If, Fn, Return, For, While, Call, MethodCall,
    BinOp, UnaryOp, Pipe, String, Number, Bool, Identifier,
    Array, Index, Assign,
)


PRELUDE = '''"""Auto-generated by Sovereign Script Compiler."""
import json, time, math, re, hashlib, datetime, random

# ── Sovereign Builtins ──────────────────────────────────
_CORTEX = None
_EMIT_QUEUE = []

def cx_remember(content, tags=None, importance=0.5):
    """Store a memory in the cortex."""
    if _CORTEX:
        from cortex import MemoryType
        return _CORTEX.remember(
            content=str(content),
            memory_type=MemoryType.EPISODIC,
            tags=tags or [],
            importance=importance,
            source="pipeline",
        )
    return None

def cx_recall(query, limit=5):
    """Search cortex memories."""
    if _CORTEX:
        results = _CORTEX.recall(str(query), limit=limit)
        return [{"content": m.content, "tags": m.tags} for m in results]
    return []

def cx_has_seen(target):
    """Check if a target appears in cortex."""
    if _CORTEX:
        results = _CORTEX.recall(str(target), limit=1)
        return len(results) > 0
    return False

def sov_emit(event, data=None):
    """Queue an event emission."""
    _EMIT_QUEUE.append({"event": event, "data": data or {}})

def sov_run(pipeline_name):
    """Placeholder — run another pipeline by name."""
    print(f"[sov_run] {pipeline_name}")

# ── End Prelude ─────────────────────────────────────────

'''


class CodeGenError(Exception):
    pass


def generate(ast: list) -> str:
    """Generate Python code from a Sovereign Script AST."""
    gen = CodeGenerator()
    return gen.generate(ast)


class CodeGenerator:
    def __init__(self):
        self.indent = 0
        self.lines: list[str] = []

    def generate(self, ast: list) -> str:
        self.lines = [PRELUDE]
        for node in ast:
            self.emit_node(node)
            self.lines.append("")
        return "\n".join(self.lines)

    def emit(self, code: str):
        prefix = "    " * self.indent
        self.lines.append(f"{prefix}{code}")

    def emit_node(self, node):
        if isinstance(node, Pipeline):
            self.emit_pipeline(node)
        elif isinstance(node, Let):
            self.emit_let(node)
        elif isinstance(node, If):
            self.emit_if(node)
        elif isinstance(node, Fn):
            self.emit_fn(node)
        elif isinstance(node, Return):
            self.emit_return(node)
        elif isinstance(node, For):
            self.emit_for(node)
        elif isinstance(node, While):
            self.emit_while(node)
        elif isinstance(node, Assign):
            self.emit(f"{node.name} = {self.expr(node.value)}")
        else:
            # Expression statement
            self.emit(self.expr(node))

    def emit_pipeline(self, node: Pipeline):
        self.emit(f"def pipeline_{node.name}():")
        self.indent += 1
        if not node.body:
            self.emit("pass")
        for stmt in node.body:
            self.emit_node(stmt)
        self.indent -= 1
        self.emit("")
        self.emit(f"# Auto-execute pipeline")
        self.emit(f"_result = pipeline_{node.name}()")

    def emit_let(self, node: Let):
        self.emit(f"{node.name} = {self.expr(node.value)}")

    def emit_if(self, node: If):
        self.emit(f"if {self.expr(node.condition)}:")
        self.indent += 1
        if not node.then_body:
            self.emit("pass")
        for stmt in node.then_body:
            self.emit_node(stmt)
        self.indent -= 1
        if node.else_body:
            self.emit("else:")
            self.indent += 1
            for stmt in node.else_body:
                self.emit_node(stmt)
            self.indent -= 1

    def emit_fn(self, node: Fn):
        params = ", ".join(node.params)
        self.emit(f"def {node.name}({params}):")
        self.indent += 1
        if not node.body:
            self.emit("pass")
        for stmt in node.body:
            self.emit_node(stmt)
        self.indent -= 1

    def emit_return(self, node: Return):
        self.emit(f"return {self.expr(node.value)}")

    def emit_for(self, node: For):
        self.emit(f"for {node.var} in {self.expr(node.iterable)}:")
        self.indent += 1
        if not node.body:
            self.emit("pass")
        for stmt in node.body:
            self.emit_node(stmt)
        self.indent -= 1

    def emit_while(self, node: While):
        self.emit(f"while {self.expr(node.condition)}:")
        self.indent += 1
        if not node.body:
            self.emit("pass")
        for stmt in node.body:
            self.emit_node(stmt)
        self.indent -= 1

    def expr(self, node) -> str:
        """Convert an expression node to a Python expression string."""
        if isinstance(node, Number):
            return repr(node.value)
        if isinstance(node, String):
            return repr(node.value)
        if isinstance(node, Bool):
            return "True" if node.value else "False"
        if isinstance(node, Identifier):
            return node.name
        if isinstance(node, Array):
            elements = ", ".join(self.expr(e) for e in node.elements)
            return f"[{elements}]"
        if isinstance(node, BinOp):
            return f"({self.expr(node.left)} {node.op} {self.expr(node.right)})"
        if isinstance(node, UnaryOp):
            return f"({node.op} {self.expr(node.operand)})"
        if isinstance(node, Call):
            args = ", ".join(self.expr(a) for a in node.args)
            return f"{node.name}({args})"
        if isinstance(node, MethodCall):
            args = ", ".join(self.expr(a) for a in node.args)
            return f"{self.expr(node.object)}.{node.method}({args})"
        if isinstance(node, Index):
            return f"{self.expr(node.object)}[{self.expr(node.index)}]"
        if isinstance(node, Pipe):
            # |> desugars to: right(left)
            right_expr = self.expr(node.right)
            left_expr = self.expr(node.left)
            return f"{right_expr}({left_expr})"
        raise CodeGenError(f"Unknown expression node: {type(node).__name__}")
